# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2bbff22ec8945eedb64e261187b92eccd29a3dd46a69db4db898c6760fb756891af4831d1d4ac38b5cfa0db3520f82b2c77ac023e8cbd610d47183d945bfb084

test:
  secret_key_base: 7f64be00e75fc4e2516237b3eaf2ae23f7a215f5dc3a2f2fd86938280779a6479cd38e7cfcf6a1fe6f50606b3229cbd3cf0fad71cd9b6e0d566c9028abbc47f4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
